import { db } from "./db";
import { zuluFieldLabels } from "@shared/schema";
import { sql } from "drizzle-orm";
import { log } from "./index";

const FIELD_LABELS_DATA: { fieldName: string; label: string; category: string | null }[] = [
  { fieldName: "Adres", label: "Адрес", category: null },
  { fieldName: "Name", label: "Наименование", category: null },
  { fieldName: "Name_pred", label: "Наименование предприятия", category: null },
  { fieldName: "Nist", label: "Номер источника", category: null },
  { fieldName: "Sist", label: "Номер источника (строка)", category: null },
  { fieldName: "H_geo", label: "Геодезическая отметка, м", category: null },
  { fieldName: "H_geo2", label: "Геодезическая отметка конца, м", category: null },
  { fieldName: "Sys", label: "Системный номер", category: null },
  { fieldName: "ZMode", label: "Режим расчёта", category: null },
  { fieldName: "ZType", label: "Тип объекта", category: null },
  { fieldName: "Nomer_uch", label: "Номер участка", category: null },
  { fieldName: "Dw_obr", label: "Толщина стенки обр. тр-да, м", category: null },
  { fieldName: "Dw_pod", label: "Толщина стенки под. тр-да, м", category: null },
  { fieldName: "FIELD1", label: "Дополнительное поле 1", category: null },
  { fieldName: "FIELD2", label: "Дополнительное поле 2", category: null },
  { fieldName: "FIELD3", label: "Дополнительное поле 3", category: null },
  { fieldName: "FIELD4", label: "Дополнительное поле 4", category: null },
  { fieldName: "FIELD5", label: "Дополнительное поле 5", category: null },
  { fieldName: "FIELD6", label: "Дополнительное поле 6", category: null },
  { fieldName: "FIELD7", label: "Дополнительное поле 7", category: null },
  { fieldName: "FIELD8", label: "Дополнительное поле 8", category: null },
  { fieldName: "UseNorma", label: "Использовать нормы", category: null },
  { fieldName: "dafter", label: "Диаметр после, м", category: null },
  { fieldName: "dbefore", label: "Диаметр до, м", category: null },
  { fieldName: "Dcalibr_o", label: "Калибровочный диаметр обр., м", category: null },
  { fieldName: "Dcalibr_p", label: "Калибровочный диаметр под., м", category: null },
  { fieldName: "Drating_c", label: "Диаметр расч. (констр.), м", category: null },
  { fieldName: "Drel_cali", label: "Относительный калибровочный диаметр", category: null },
  { fieldName: "LeakZeta_", label: "Коэфф. местного сопр. утечки", category: null },
  { fieldName: "Overgrowt", label: "Зарастание, мм", category: null },
  { fieldName: "Zrating_c", label: "Сумма коэф. местных сопр. (констр.)", category: null },
  { fieldName: "Gcalibr_o", label: "Калибровочный расход обр., т/ч", category: null },
  { fieldName: "Gcalibr_p", label: "Калибровочный расход под., т/ч", category: null },
  { fieldName: "Pcalibr_o", label: "Калибровочное давление обр., м", category: null },
  { fieldName: "Pcalibr_p", label: "Калибровочное давление под., м", category: null },
  { fieldName: "Tcalibr_o", label: "Калибровочная температура обр., °C", category: null },
  { fieldName: "Tcalibr_p", label: "Калибровочная температура под., °C", category: null },
  { fieldName: "G1_t", label: "Текущий расход 1 контура, т/ч", category: null },
  { fieldName: "G2_t", label: "Текущий расход 2 контура, т/ч", category: null },
  { fieldName: "Gt_obr", label: "Расход в обратном тр-де (текущий), т/ч", category: null },
  { fieldName: "T11_t", label: "Текущая температура на входе 1 контура, °C", category: null },
  { fieldName: "T12_t", label: "Текущая температура на выходе 1 контура, °C", category: null },
  { fieldName: "Tcut", label: "Температура среза, °C", category: null },
  { fieldName: "Tshelf", label: "Температура полки, °C", category: null },
  { fieldName: "Ttunnel", label: "Температура в тоннеле, °C", category: null },
  { fieldName: "Tsg_tunnel", label: "Среднегодовая температура в тоннеле, °C", category: null },
  { fieldName: "Qniz", label: "Нагрузка нижней ступени", category: null },
  { fieldName: "Qverh", label: "Нагрузка верхней ступени", category: null },
  { fieldName: "Qcirc_c", label: "Расход на циркуляцию (расч.), т/ч", category: null },
  { fieldName: "Qso_c", label: "Нагрузка на СО (расч.), Гкал/ч", category: null },
  { fieldName: "Qsv_c", label: "Нагрузка на СВ (расч.), Гкал/ч", category: null },
  { fieldName: "Qgv_c", label: "Нагрузка на ГВС (расч.), Гкал/ч", category: null },
  { fieldName: "Qsum_c", label: "Суммарная нагрузка (расч.), Гкал/ч", category: null },
  { fieldName: "Regul_G_k", label: "Kvs способа дросселирования", category: null },
  { fieldName: "Regul_T_k", label: "Kvs регулятора температуры", category: null },
  { fieldName: "RegulVal", label: "Значение регулятора", category: null },
  { fieldName: "Lambda_r_", label: "Расчетная интенсивность отказов", category: null },
  { fieldName: "Lambda_t_", label: "Средняя интенсивность отказов", category: null },
  { fieldName: "T1_r", label: "Расчетная температура в подающем тр-де, °С", category: null },
  { fieldName: "Thz_r", label: "Расчетная температура холодной воды, °С", category: null },
  { fieldName: "Tnv_r", label: "Расчетная температура наружного воздуха, °С", category: null },
  { fieldName: "T1_t", label: "Текущая температура воды в подающем тр-де, °С", category: null },
  { fieldName: "Tnv_t", label: "Текущая температура наружного воздуха, °С", category: null },
  { fieldName: "H_ras", label: "Располагаемый напор, м", category: null },
  { fieldName: "H_obr", label: "Напор в обратном трубопроводе, м", category: null },
  { fieldName: "Mode", label: "Режим работы источника", category: null },
  { fieldName: "H_pod", label: "Напор в подающем трубопроводе, м", category: null },
  { fieldName: "Gpod", label: "Слив/Расход в подающем тр-де, т/ч", category: null },
  { fieldName: "Gobr", label: "Слив/Расход в обратном тр-де, т/ч", category: null },
  { fieldName: "Tpod", label: "Температура воды в подающем тр-де, °C", category: null },
  { fieldName: "Tobr", label: "Температура воды в обратном тр-де, °C", category: null },
  { fieldName: "Ppod", label: "Давление в подающем тр-де, м", category: null },
  { fieldName: "Pobr", label: "Давление в обратном тр-де, м", category: null },
  { fieldName: "Time", label: "Время прохождения воды от источника, мин", category: null },
  { fieldName: "Dist", label: "Путь, пройденный от источника, м", category: null },
  { fieldName: "Tb", label: "Давление вскипания, м", category: null },
  { fieldName: "Hstat", label: "Статический напор, м", category: null },
  { fieldName: "Owner", label: "Балансодержатель", category: null },
  { fieldName: "Begin_uch", label: "Наименование начала участка", category: null },
  { fieldName: "End_uch", label: "Наименование конца участка", category: null },
  { fieldName: "L", label: "Длина участка, м", category: null },
  { fieldName: "Dpod", label: "Диаметр подающего тр-да, м", category: null },
  { fieldName: "Dobr", label: "Диаметр обратного тр-да, м", category: null },
  { fieldName: "Zpod", label: "Сумма коэф. местных сопр. под. тр-да", category: null },
  { fieldName: "Zpod_str", label: "Местные сопротивления под. тр-да", category: null },
  { fieldName: "Zobr", label: "Сумма коэф. местных сопр. обр. тр-да", category: null },
  { fieldName: "Zobr_str", label: "Местные сопротивления обр. тр-да", category: null },
  { fieldName: "Ke_pod", label: "Шероховатость подающего тр-да, мм", category: null },
  { fieldName: "Ke_obr", label: "Шероховатость обратного тр-да, мм", category: null },
  { fieldName: "Zarost_pod", label: "Зарастание подающего тр-да, мм", category: null },
  { fieldName: "Zarost_obr", label: "Зарастание обратного тр-да, мм", category: null },
  { fieldName: "Kz_pod", label: "Коэфф. местного сопр. под. тр-да", category: null },
  { fieldName: "Kz_obr", label: "Коэфф. местного сопр. обр. тр-да", category: null },
  { fieldName: "Spod", label: "Сопротивление подающего тр-да, м/(т/ч)²", category: null },
  { fieldName: "Sobr", label: "Сопротивление обратного тр-да, м/(т/ч)²", category: null },
  { fieldName: "StatZone", label: "Разделитель зон статическим напором", category: null },
  { fieldName: "Options", label: "Опции", category: null },
  { fieldName: "Proklad", label: "Вид прокладки тепловой сети", category: null },
  { fieldName: "Norma", label: "Нормативные потери в тепловой сети", category: null },
  { fieldName: "Use_pod", label: "Период работы подающего тр-да", category: null },
  { fieldName: "Use_obr", label: "Период работы обратного тр-да", category: null },
  { fieldName: "Kpoprav", label: "Поправочный коэфф. тепл. потерь под. тр-да", category: null },
  { fieldName: "Kpop_obr", label: "Поправочный коэфф. тепл. потерь обр. тр-да", category: null },
  { fieldName: "Grunt", label: "Вид грунта", category: null },
  { fieldName: "Hzal", label: "Глубина заложения трубопровода, м", category: null },
  { fieldName: "Izol_pod", label: "Теплоизоляционный материал под. тр-да", category: null },
  { fieldName: "Izol_obr", label: "Теплоизоляционный материал обр. тр-да", category: null },
  { fieldName: "Wizol_pod", label: "Толщина изоляции подающего тр-да, м", category: null },
  { fieldName: "Wizol_obr", label: "Толщина изоляции обратного тр-да, м", category: null },
  { fieldName: "Tex_pod", label: "Техническое состояние изоляции под. тр-да", category: null },
  { fieldName: "Tex_obr", label: "Техническое состояние изоляции обр. тр-да", category: null },
  { fieldName: "S", label: "Расстояние между осями трубопроводов, м", category: null },
  { fieldName: "Hkanal", label: "Высота канала, м", category: null },
  { fieldName: "Wkanal", label: "Ширина канала, м", category: null },
  { fieldName: "Q1_pod", label: "Доп. потери тепла под. тр-да, ккал", category: null },
  { fieldName: "Q1_obr", label: "Доп. потери тепла обр. тр-да, ккал", category: null },
  { fieldName: "dH_pod", label: "Потери напора в подающем тр-де, м", category: null },
  { fieldName: "dH_obr", label: "Потери напора в обратном тр-де, м", category: null },
  { fieldName: "Ppod_beg", label: "Давление в начале подающего, м", category: null },
  { fieldName: "Ppod_end", label: "Давление в конце подающего, м", category: null },
  { fieldName: "Pobr_beg", label: "Давление в начале обратного, м", category: null },
  { fieldName: "Pobr_end", label: "Давление в конце обратного, м", category: null },
  { fieldName: "Hpod_beg", label: "Напор в начале подающего, м", category: null },
  { fieldName: "Hpod_end", label: "Напор в конце подающего, м", category: null },
  { fieldName: "Hobr_beg", label: "Напор в начале обратного, м", category: null },
  { fieldName: "Hobr_end", label: "Напор в конце обратного, м", category: null },
  { fieldName: "Hras_beg", label: "Располагаемый напор в начале, м", category: null },
  { fieldName: "Hras_end", label: "Располагаемый напор в конце, м", category: null },
  { fieldName: "dHud_pod", label: "Удельные линейные потери напора в под. тр-де, мм/м", category: null },
  { fieldName: "dHud_obr", label: "Удельные линейные потери напора в обр. тр-де, мм/м", category: null },
  { fieldName: "Le_pod", label: "Эквивалентная длина подающего, м", category: null },
  { fieldName: "Le_obr", label: "Эквивалентная длина обратного, м", category: null },
  { fieldName: "Lt_pod", label: "Приведенная длина подающего, м", category: null },
  { fieldName: "Lt_obr", label: "Приведенная длина обратного, м", category: null },
  { fieldName: "Re_pod", label: "Число Рейнольдса на подающем", category: null },
  { fieldName: "Re_obr", label: "Число Рейнольдса на обратном", category: null },
  { fieldName: "Lambda_pod", label: "Коэфф. гидравл. трения на подающем", category: null },
  { fieldName: "Lambda_obr", label: "Коэфф. гидравл. трения на обратном", category: null },
  { fieldName: "Vpod", label: "Скорость воды в под. тр-де, м/с", category: null },
  { fieldName: "Vobr", label: "Скорость воды в обр. тр-де, м/с", category: null },
  { fieldName: "Gut_pod", label: "Утечка из подающего тр-да, т/ч", category: null },
  { fieldName: "Gut_obr", label: "Утечка из обратного тр-да, т/ч", category: null },
  { fieldName: "Qpot_pod", label: "Тепловые потери в подающем тр-де, ккал/ч", category: null },
  { fieldName: "Qpot_obr", label: "Тепловые потери в обратном тр-де, ккал/ч", category: null },
  { fieldName: "Tbeg_pod", label: "Температура в начале участка под. тр-да, °C", category: null },
  { fieldName: "Tend_pod", label: "Температура в конце участка под. тр-да, °C", category: null },
  { fieldName: "Tbeg_obr", label: "Температура в начале участка обр. тр-да, °C", category: null },
  { fieldName: "Tend_obr", label: "Температура в конце участка обр. тр-да, °C", category: null },
  { fieldName: "Tsurf", label: "Температура на поверхности, °С", category: null },
  { fieldName: "Drek_pod", label: "Диаметр под. тр-да (конструкторский), м", category: null },
  { fieldName: "Drek_obr", label: "Диаметр обр. тр-да (конструкторский), м", category: null },
  { fieldName: "Ke_con_pod", label: "Шероховатость под. тр-да (конструкторский), мм", category: null },
  { fieldName: "Ke_con_obr", label: "Шероховатость обр. тр-да (конструкторский), мм", category: null },
  { fieldName: "Vopt_pod", label: "Оптимальная скорость в подающем (констр.), м/с", category: null },
  { fieldName: "Vopt_obr", label: "Оптимальная скорость в обратном (констр.), м/с", category: null },
  { fieldName: "dHud_con_pod", label: "Удельные линейные потери подающего (констр.), мм/м", category: null },
  { fieldName: "dHud_con_obr", label: "Удельные линейные потери обратного (констр.), мм/м", category: null },
  { fieldName: "Tubes", label: "Сортамент", category: null },
  { fieldName: "DFixed", label: "Фиксированный диаметр (конструкторский)", category: null },
  { fieldName: "Lper", label: "Длина перемычки, м", category: null },
  { fieldName: "Dper", label: "Диаметр перемычки, м", category: null },
  { fieldName: "Zper", label: "Коэф. местных сопротивлений перемычки", category: null },
  { fieldName: "Kper", label: "Шероховатость перемычки, мм", category: null },
  { fieldName: "Sper", label: "Сопротивление перемычки, м·ч²/т²", category: null },
  { fieldName: "Gperem", label: "Расход воды по перемычке, т/ч", category: null },
  { fieldName: "Dshb_pod", label: "Диаметр шайбы на под. тр-де, мм", category: null },
  { fieldName: "Nshb_pod", label: "Количество шайб на под. тр-де, шт", category: null },
  { fieldName: "Dshb_obr", label: "Диаметр шайбы на обр. тр-де, мм", category: null },
  { fieldName: "Nshb_obr", label: "Количество шайб на обр. тр-де, шт", category: null },
  { fieldName: "Dbp_pod", label: "Диаметр байпаса на подающем тр-де, м", category: null },
  { fieldName: "Lbp_pod", label: "Длина байпаса на подающем тр-де, м", category: null },
  { fieldName: "Dbp_obr", label: "Диаметр байпаса на обратном тр-де, м", category: null },
  { fieldName: "Lbp_obr", label: "Длина байпаса на обратном тр-де, м", category: null },
  { fieldName: "Zbp_pod", label: "Сумма коэф. местных сопр. байпаса под. тр-да", category: null },
  { fieldName: "Zbp_obr", label: "Сумма коэф. местных сопр. байпаса обр. тр-да", category: null },
  { fieldName: "Kv_pod", label: "Kv байпаса на подающем, м³/ч", category: null },
  { fieldName: "Kv_obr", label: "Kv байпаса на обратном, м³/ч", category: null },
  { fieldName: "Ke_bp", label: "Шероховатость байпаса, мм", category: null },
  { fieldName: "Hzapas", label: "Запас напора, м", category: null },
  { fieldName: "Regul_G", label: "Способ дросселирования", category: null },
  { fieldName: "H", label: "Регулируемый параметр напор/расход", category: null },
  { fieldName: "Kreg", label: "Пропускная способность регулятора", category: null },
  { fieldName: "Deq", label: "Диаметр эквивалентной шайбы, мм", category: null },
  { fieldName: "Hin", label: "Располагаемый напор до узла, м", category: null },
  { fieldName: "Hout", label: "Располагаемый напор после узла, м", category: null },
  { fieldName: "Hin_pod", label: "Напор в подающем тр-де перед узлом, м", category: null },
  { fieldName: "Hout_pod", label: "Напор в подающем тр-де после узла, м", category: null },
  { fieldName: "Hin_obr", label: "Напор в обратном тр-де перед узлом, м", category: null },
  { fieldName: "Hout_obr", label: "Напор в обратном тр-де после узла, м", category: null },
  { fieldName: "dHshb_pod", label: "Потери напора на шайбе в под. тр., м", category: null },
  { fieldName: "dHshb_obr", label: "Потери напора на шайбе в обр. тр., м", category: null },
  { fieldName: "Pin_pod", label: "Давление в подающем тр-де перед узлом, м", category: null },
  { fieldName: "Pout_pod", label: "Давление в подающем тр-де после узла, м", category: null },
  { fieldName: "Pin_obr", label: "Давление в обратном тр-де перед узлом, м", category: null },
  { fieldName: "Pout_obr", label: "Давление в обратном тр-де после узла, м", category: null },
  { fieldName: "Hstat_out", label: "Статический напор на выходе, м", category: null },
  { fieldName: "Type_pod", label: "Способ задания насоса на подающем", category: null },
  { fieldName: "Mark_pod", label: "Марка насоса/арматуры на подающем", category: null },
  { fieldName: "Npod", label: "Число насосов на подающем тр-де", category: null },
  { fieldName: "Hpod", label: "Напор насоса на подающем тр-де, м", category: null },
  { fieldName: "Pr_pod", label: "Напор после насоса на подающем, м", category: null },
  { fieldName: "Type_obr", label: "Способ задания насоса на обратном", category: null },
  { fieldName: "Mark_obr", label: "Марка насоса/арматуры на обратном", category: null },
  { fieldName: "Nobr", label: "Число насосов на обратном тр-де", category: null },
  { fieldName: "Hobr", label: "Напор насоса на обратном тр-де, м", category: null },
  { fieldName: "Pr_obr", label: "Напор перед насосом на обратном, м", category: null },
  { fieldName: "Cost_w", label: "Стоимость электроэнергии", category: null },
  { fieldName: "Costs_w", label: "Затраты на электроэнергию", category: null },
  { fieldName: "Per_pod", label: "Степень открытия на подающем", category: null },
  { fieldName: "Per_obr", label: "Степень открытия на обратном", category: null },
  { fieldName: "Hzdan", label: "Высота здания потребителя, м", category: null },
  { fieldName: "N_schem", label: "Номер схемы подключения", category: null },
  { fieldName: "Qo_r", label: "Расчетная нагрузка на отопление, Гкал/ч", category: null },
  { fieldName: "Qsv_r", label: "Расчетная нагрузка на вентиляцию, Гкал/ч", category: null },
  { fieldName: "Qgv_sred", label: "Расчетная средняя нагрузка на ГВС, Гкал/ч", category: null },
  { fieldName: "Njil", label: "Число жителей", category: null },
  { fieldName: "Kso", label: "Коэфф. изменения расхода на СО и СВ", category: null },
  { fieldName: "Ksv", label: "Коэфф. изменения расхода на СВ", category: null },
  { fieldName: "Kgv", label: "Коэфф. изменения расхода на ГВС", category: null },
  { fieldName: "Kb", label: "Балансовый коэффициент закр. ГВС", category: null },
  { fieldName: "Gso_otn_max", label: "Макс. относительный расход на СО", category: null },
  { fieldName: "Gso_max", label: "Макс. расход на СО, т/ч", category: null },
  { fieldName: "Tvso_n", label: "Начальная температура воздуха для СО, °C", category: null },
  { fieldName: "Klapan_sv", label: "Клапан на систему вентиляции", category: null },
  { fieldName: "Regul_T", label: "Наличие регулятора температуры на ГВС", category: null },
  { fieldName: "Regul_T_kvs", label: "Kvs регулятора температуры на ГВС", category: null },
  { fieldName: "T2_r", label: "Расчетная температура на входе 2 контура, °C", category: null },
  { fieldName: "T3_r", label: "Расчетная температура на выходе 2 контура, °С", category: null },
  { fieldName: "Tvso_r", label: "Расчетная температура внутр. воздуха для СО, °C", category: null },
  { fieldName: "Hso_r", label: "Расчетный располагаемый напор на СО, м", category: null },
  { fieldName: "Hso_zapas", label: "Запас напора на СО при наладке, м", category: null },
  { fieldName: "Tvsv_r", label: "Расчетная температура внутр. воздуха для СВ, °C", category: null },
  { fieldName: "Tnsv_r", label: "Расчетная температура наружного воздуха для СВ, °С", category: null },
  { fieldName: "Hsv_r", label: "Расчетный располагаемый напор в СВ, м", category: null },
  { fieldName: "Kcirc", label: "Коэфф. циркуляции", category: null },
  { fieldName: "Hcirc", label: "Потери напора в циркуляционном контуре, м", category: null },
  { fieldName: "Hpump_gvs", label: "Напор циркуляционного насоса ГВС, м", category: null },
  { fieldName: "Tcirc", label: "Температура циркуляции, °C", category: null },
  { fieldName: "Thv", label: "Расчетная температура холодной воды, °С", category: null },
  { fieldName: "Tgv", label: "Расчетная температура горячей воды, °С", category: null },
  { fieldName: "Pmax_obr", label: "Макс. давление в обратном тр-де, м", category: null },
  { fieldName: "Pmax_gvs", label: "Макс. давление в системе ГВС, м", category: null },
  { fieldName: "Thv_t", label: "Текущая температура холодной воды, °С", category: null },
  { fieldName: "Nsec_so", label: "Количество секций ТО на СО", category: null },
  { fieldName: "Hsec_so", label: "Потери напора в секции ТО на СО, м", category: null },
  { fieldName: "Ngr_so", label: "Количество параллельных групп ТО на СО", category: null },
  { fieldName: "T1to_so", label: "Расчетная температура на выходе 1 контура СО, °C", category: null },
  { fieldName: "T2r_obr", label: "Расчетная температура в обратном тр-де СО, °C", category: null },
  { fieldName: "Tto_so", label: "Температура теплоносителя после ТО на СО, °C", category: null },
  { fieldName: "Nel_r", label: "Расчетное количество элементов смешения", category: null },
  { fieldName: "Dsop_r", label: "Расчетный диаметр сопла, мм", category: null },
  { fieldName: "U_calc", label: "Расчетный коэфф. смешения", category: null },
  { fieldName: "U_fakt", label: "Фактический коэфф. смешения", category: null },
  { fieldName: "Nel_u", label: "Количество элементов смешения (факт.)", category: null },
  { fieldName: "Dsop_u", label: "Диаметр сопла (факт.), мм", category: null },
  { fieldName: "T1_t_consumer", label: "Текущая температура в подающем тр-де, °С", category: null },
  { fieldName: "T2_t", label: "Текущая температура в обратном тр-де, °С", category: null },
  { fieldName: "Gso", label: "Расход сетевой воды на СО, т/ч", category: null },
  { fieldName: "Gso_otn", label: "Относительный расход воды на СО", category: null },
  { fieldName: "Qso_otn", label: "Относительная нагрузка на СО", category: null },
  { fieldName: "T3so_t", label: "Температура после смесительного устройства на СО, °C", category: null },
  { fieldName: "T2so_t", label: "Температура воды после системы отопления, °C", category: null },
  { fieldName: "Tvso_t", label: "Температура внутреннего воздуха СО, °C", category: null },
  { fieldName: "Dshb_so_pod", label: "Диаметр шайбы на СО в под. тр-де, мм", category: null },
  { fieldName: "Nshb_so_pod", label: "Количество шайб на СО в под. тр-де, шт", category: null },
  { fieldName: "Dshb_so_obr", label: "Диаметр шайбы на СО в обр. тр-де, мм", category: null },
  { fieldName: "Nshb_so_obr", label: "Количество шайб на СО в обр. тр-де, шт", category: null },
  { fieldName: "dHshb_so_pod", label: "Потери напора на шайбе СО в под. тр., м", category: null },
  { fieldName: "dHshb_so_obr", label: "Потери напора на шайбе СО в обр. тр., м", category: null },
  { fieldName: "dHsop", label: "Потери напора на сопле, м", category: null },
  { fieldName: "dHsoplo", label: "Потери напора на сопле, м", category: null },
  { fieldName: "Gsv", label: "Расход сетевой воды на СВ, т/ч", category: null },
  { fieldName: "Gsv_otn", label: "Относительный расход воды на СВ", category: null },
  { fieldName: "T2sv_t", label: "Температура воды после системы вентиляции, °C", category: null },
  { fieldName: "Tvsv_t", label: "Температура внутреннего воздуха СВ, °C", category: null },
  { fieldName: "Dshb_sv", label: "Диаметр шайбы на систему вентиляции, мм", category: null },
  { fieldName: "Nshb_sv", label: "Количество шайб на систему вентиляции, шт", category: null },
  { fieldName: "dHshb_sv", label: "Потери напора на шайбе СВ, м", category: null },
  { fieldName: "Ggv", label: "Расход сетевой воды на открытые ГВС, т/ч", category: null },
  { fieldName: "Tgv_t", label: "Текущая температура воды на ГВС, °C", category: null },
  { fieldName: "Gcirc", label: "Расход воды в цирк. трубопроводе, т/ч", category: null },
  { fieldName: "Tcirc_t", label: "Текущая температура воды в цирк. контуре, °C", category: null },
  { fieldName: "Dshb_gvs", label: "Диаметр шайбы на ГВС, мм", category: null },
  { fieldName: "Nshb_gvs", label: "Количество шайб на ГВС, шт", category: null },
  { fieldName: "dHshb_gvs", label: "Потери напора на шайбе ГВС, м", category: null },
  { fieldName: "Dshb_circ", label: "Диаметр циркуляционной шайбы на ГВС, мм", category: null },
  { fieldName: "Nshb_circ", label: "Количество циркуляционных шайб на ГВС, шт", category: null },
  { fieldName: "Dshb_so_pod_u", label: "Диаметр шайбы СО на подающем (факт.), мм", category: null },
  { fieldName: "Nshb_so_pod_u", label: "Количество шайб СО на подающем (факт.), шт", category: null },
  { fieldName: "Dshb_so_obr_u", label: "Диаметр шайбы СО на обратном (факт.), мм", category: null },
  { fieldName: "Nshb_so_obr_u", label: "Количество шайб СО на обратном (факт.), шт", category: null },
  { fieldName: "dHsnb_so_obr", label: "Потери напора на шайбе обр. тр-да после СО, м", category: null },
  { fieldName: "Nsec_niz", label: "Количество секций ТО ГВС I ступень", category: null },
  { fieldName: "Ngr_niz", label: "Количество паралл. групп ТО ГВС I ступень", category: null },
  { fieldName: "Hsec_niz", label: "Потери напора в секции I ступени, м", category: null },
  { fieldName: "T11_i_niz", label: "Исп. температура на входе 1 контура I ступени, °C", category: null },
  { fieldName: "T12_i_niz", label: "Исп. температура на выходе 1 контура I ступени, °C", category: null },
  { fieldName: "T21_i_niz", label: "Исп. температура на входе 2 контура I ступени, °C", category: null },
  { fieldName: "T22_i_niz", label: "Исп. температура на выходе 2 контура I ступени, °C", category: null },
  { fieldName: "Q_i_niz", label: "Исп. тепловая нагрузка I ступени, Гкал/час", category: null },
  { fieldName: "Gniz", label: "Расход 1 контура I ступени ТО ГВС, т/ч", category: null },
  { fieldName: "G2_niz", label: "Расход 2 контура I ступени ТО ГВС, т/ч", category: null },
  { fieldName: "Q_niz", label: "Тепловая нагрузка I ступени, Гкал/час", category: null },
  { fieldName: "T11_niz", label: "Температура на входе 1 контура I ступени, °C", category: null },
  { fieldName: "T12_niz", label: "Температура на выходе 1 контура I ступени, °C", category: null },
  { fieldName: "T21_niz", label: "Температура на входе 2 контура I ступени, °C", category: null },
  { fieldName: "T22_niz", label: "Температура на выходе 2 контура I ступени, °C", category: null },
  { fieldName: "Nsec_verh", label: "Количество секций ТО ГВС II ступень", category: null },
  { fieldName: "Ngr_verh", label: "Количество паралл. групп ТО ГВС II ступень", category: null },
  { fieldName: "Hsec_verh", label: "Потери напора в секции II ступени, м", category: null },
  { fieldName: "T11_i_verh", label: "Исп. температура на входе 1 контура II ступени, °C", category: null },
  { fieldName: "T12_i_verh", label: "Исп. температура на выходе 1 контура II ступени, °C", category: null },
  { fieldName: "T21_i_verh", label: "Исп. температура на входе 2 контура II ступени, °C", category: null },
  { fieldName: "T22_i_verh", label: "Исп. температура на выходе 2 контура II ступени, °C", category: null },
  { fieldName: "Q_i_verh", label: "Исп. тепловая нагрузка II ступени, Гкал/час", category: null },
  { fieldName: "T11_verh", label: "Температура на входе 1 контура II ступени, °C", category: null },
  { fieldName: "T12_verh", label: "Температура на выходе 1 контура II ступени, °C", category: null },
  { fieldName: "T21_verh", label: "Температура на входе 2 контура II ступени, °C", category: null },
  { fieldName: "T22_verh", label: "Температура на выходе 2 контура II ступени, °C", category: null },
  { fieldName: "Gverh", label: "Расход 1 контура II ступени ТО ГВС, т/ч", category: null },
  { fieldName: "G2_verh", label: "Расход 2 контура II ступени ТО ГВС, т/ч", category: null },
  { fieldName: "Q_verh", label: "Тепловая нагрузка II ступени, Гкал/час", category: null },
  { fieldName: "Gset_nal", label: "Расход сетевой воды после наладки, т/ч", category: null },
  { fieldName: "Hset_nal", label: "Напор на регуляторе давления СО, м", category: null },
  { fieldName: "Gsum_pod", label: "Суммарный расход сетевой воды, т/ч", category: null },
  { fieldName: "Q_sum", label: "Суммарная нагрузка, Гкал/час", category: null },
  { fieldName: "Gut_pot", label: "Утечка из системы теплопотребления, т/ч", category: null },
  { fieldName: "Qut_pot", label: "Потери тепла от утечки, Ккал", category: null },
  { fieldName: "Gcon_so", label: "Расчетный расход на СО (констр.), т/ч", category: null },
  { fieldName: "Gcon_sv", label: "Расчетный расход на СВ (констр.), т/ч", category: null },
  { fieldName: "Gcon_gv", label: "Расчетный на циркуляцию ГВС (констр.), т/ч", category: null },
  { fieldName: "Gcon_gv_open", label: "Разбор воды на ГВС (констр.), т/ч", category: null },
  { fieldName: "Hcon_ras", label: "Располагаемый напор на вводе (констр.), м", category: null },
  { fieldName: "T1to_so_ctp", label: "Расчетная температура на выходе 1 контура СО, °C", category: null },
  { fieldName: "Hnz_ras", label: "Располагаемый напор второго контура, м", category: null },
  { fieldName: "Hnz_obr", label: "Напор в обратке второго контура, м", category: null },
  { fieldName: "Podpit", label: "Подпитка второго контура", category: null },
  { fieldName: "Dshb_pod_u", label: "Диаметр шайбы на подающем (факт.), мм", category: null },
  { fieldName: "Nshb_pod_u", label: "Количество шайб на подающем (факт.), шт", category: null },
  { fieldName: "Dshb_obr_u", label: "Диаметр шайбы на обратном (факт.), мм", category: null },
  { fieldName: "Nshb_obr_u", label: "Количество шайб на обратном (факт.), шт", category: null },
  { fieldName: "Dshb_gvs_u", label: "Диаметр шайбы на ГВС (факт.), мм", category: null },
  { fieldName: "Nshb_gvs_u", label: "Количество шайб на ГВС (факт.), шт", category: null },
  { fieldName: "Hgv2_ras", label: "Располагаемый напор на ГВС 2 контура, м", category: null },
  { fieldName: "Hgv2_obr", label: "Напор в обратке ГВС 2 контура, м", category: null },
  { fieldName: "Qo_t", label: "Подключенная нагрузка на отопление, Гкал/ч", category: null },
  { fieldName: "Qsv_t", label: "Подключенная нагрузка на вентиляцию, Гкал/ч", category: null },
  { fieldName: "Qgv_t", label: "Подключенная нагрузка на ГВС, Гкал/ч", category: null },
  { fieldName: "Hgv_pod", label: "Напор в под. тр-де ГВС, м", category: null },
  { fieldName: "Hgv_obr", label: "Напор в обр. тр-де ГВС, м", category: null },
  { fieldName: "Pgv_pod", label: "Давление в под. тр-де ГВС, м", category: null },
  { fieldName: "Pgv_obr", label: "Давление в обр. тр-де ГВС, м", category: null },
  { fieldName: "RegulType", label: "Тип регулятора", category: null },
  { fieldName: "Tsg_pod", label: "Среднегодовая температура воды в под. тр-де, °С", category: null },
  { fieldName: "Tsg_obr", label: "Среднегодовая температура воды в обр. тр-де, °С", category: null },
  { fieldName: "Tsg_grunt", label: "Среднегодовая температура грунта, °C", category: null },
  { fieldName: "Tsg_nv", label: "Среднегодовая температура наружного воздуха, °С", category: null },
  { fieldName: "Tsg_podval", label: "Среднегодовая температура воздуха в подвалах, °C", category: null },
  { fieldName: "Tgrunt", label: "Текущая температура грунта, °C", category: null },
  { fieldName: "Tpodval", label: "Текущая температура воздуха в подвалах, °C", category: null },
  { fieldName: "Gsum_pod2", label: "Суммарный расход воды во 2 контуре ЦТП, т/ч", category: null },
  { fieldName: "Qut_pod", label: "Потери тепла от утечек в подающем тр-де, Ккал/ч", category: null },
  { fieldName: "Qut_obr", label: "Потери тепла от утечек в обратном тр-де, Ккал/ч", category: null },
  { fieldName: "Qut_potr", label: "Потери тепла от утечек в сист. теплопотреб., Ккал/ч", category: null },
  { fieldName: "T11_i", label: "Исп. температура воды на входе 1 контура, °C", category: null },
  { fieldName: "T12_i", label: "Исп. температура воды на выходе 1 контура, °C", category: null },
  { fieldName: "T21_i", label: "Исп. температура воды на входе 2 контура, °C", category: null },
  { fieldName: "T22_i", label: "Исп. температура воды на выходе 2 контура, °C", category: null },
  { fieldName: "G1_i", label: "Исп. расход 1 контура, т/ч", category: null },
  { fieldName: "G2_i", label: "Исп. расход 2 контура, т/ч", category: null },
  { fieldName: "Qsum", label: "Суммарная тепловая нагрузка на ЦТП, Гкал/ч", category: null },
  { fieldName: "Qts_pod", label: "Тепловые потери в подающем тр-де, Ккал/ч", category: null },
  { fieldName: "Qts_obr", label: "Тепловые потери в обратном тр-де, Ккал/ч", category: null },
  { fieldName: "Gut_potr", label: "Расход воды на утечки из систем теплопотреб., т/ч", category: null },
  { fieldName: "Tb_out", label: "Давление вскипания на выходе ЦТП, м", category: null },
  { fieldName: "Gu_r", label: "Расход на открытый водоразбор, т/ч", category: null },
  { fieldName: "Gto_r", label: "Расход воды на закр. системы ГВС, т/ч", category: null },
  { fieldName: "Kto", label: "Коэфф. изменения расхода на закр. ГВС", category: null },
  { fieldName: "Beta", label: "Доля водоразбора из подающего тр-да", category: null },
  { fieldName: "Sr", label: "Расчетное сопротивление, м/(т/ч)²", category: null },
  { fieldName: "Tobr_type", label: "Способ определения температуры обратной воды", category: null },
  { fieldName: "Tobr_val", label: "Значение температуры обратной воды, °C", category: null },
  { fieldName: "Lambda_t_nad", label: "Средняя интенсивность отказов, 1/(км·ч)", category: null },
  { fieldName: "Lambda_r_nad", label: "Расчетная интенсивность отказов, 1/(км·ч)", category: null },
  { fieldName: "Tr_nad", label: "Расчетное время восстановления, ч", category: null },
  { fieldName: "Texp_nad", label: "Период эксплуатации, лет", category: null },
  { fieldName: "Trep_nad", label: "Время восстановления, ч", category: null },
  { fieldName: "Mrep_nad", label: "Интенсивность восстановления, 1/ч", category: null },
  { fieldName: "Lambda_nad", label: "Интенсивность отказов, 1/(км·ч)", category: null },
  { fieldName: "Omega_nad", label: "Поток отказов, 1/ч", category: null },
  { fieldName: "Qot_nad", label: "Относительное кол. отключ. нагрузки", category: null },
  { fieldName: "Pbreak_nad", label: "Вероятность отказа", category: null },
  { fieldName: "Beta_nad", label: "Коэффициент тепловой аккумуляции, ч", category: null },
  { fieldName: "Tmin_nad", label: "Минимально допустимая температура, °С", category: null },
  { fieldName: "R_nad", label: "Вероятность безотказной работы", category: null },
  { fieldName: "K_nad", label: "Коэффициент готовности", category: null },
  { fieldName: "Qlost_nad", label: "Средний суммарный недоотпуск теплоты, Гкал/от.период", category: null },
  { fieldName: "T1to_so_ist", label: "Расчетная температура на выходе 1 контура, °C", category: null },
  { fieldName: "addr_begin", label: "Адресный ориентир начала участка", category: null },
  { fieldName: "addr_end", label: "Адресный ориентир окончания участка", category: null },
  { fieldName: "addr_point", label: "Адресный ориентир", category: null },
  { fieldName: "fias_begin", label: "ФИАС ID начала участка", category: null },
  { fieldName: "fias_end", label: "ФИАС ID окончания участка", category: null },
  { fieldName: "fias_point", label: "ФИАС ID", category: null },
  { fieldName: "fias_id", label: "ФИАС ID", category: null },
  { fieldName: "cluster_id", label: "ID кластера", category: null },
  { fieldName: "complaint_count", label: "Кол-во жалоб", category: null },
  { fieldName: "radius_m", label: "Радиус (м)", category: null },
  { fieldName: "centroid_lon", label: "Долгота центра", category: null },
  { fieldName: "centroid_lat", label: "Широта центра", category: null },
  { fieldName: "addresses", label: "Адреса", category: null },
  { fieldName: "address_count", label: "Кол-во адресов", category: null },
  { fieldName: "zone_name", label: "Зона отказа", category: null },
  { fieldName: "zone_type", label: "Тип зоны", category: null },
  { fieldName: "confidence", label: "Достоверность", category: null },
  { fieldName: "downstream_consumer_count", label: "Кол-во потребителей ниже по сети", category: null },
  { fieldName: "complaint_consumers", label: "Потребители с жалобами", category: null },
  { fieldName: "segment", label: "Участок", category: null },
  { fieldName: "segment_length_m", label: "Длина участка (м)", category: null },
  { fieldName: "affected_segments_count", label: "Затронутых участков", category: null },
  { fieldName: "affected_consumers_count", label: "Затронутых потребителей", category: null },
  { fieldName: "consumer_names", label: "Имена потребителей", category: null },
  { fieldName: "consumer_addresses", label: "Адреса потребителей", category: null },
  { fieldName: "segments_detail", label: "Детали участков", category: null },
  { fieldName: "group_complaint_count", label: "Жалоб в группе", category: null },
  { fieldName: "group_consumers", label: "Потребители группы", category: null },
  { fieldName: "source_name", label: "Источник теплоснабжения", category: null },
  { fieldName: "date", label: "Дата", category: null },
  { fieldName: "ц", label: "d", category: null },
];

export async function seedFieldLabelsIfEmpty(): Promise<void> {
  try {
    const result = await db.execute(
      sql`SELECT COUNT(*)::text AS count FROM zulu_field_labels`
    );
    const count = parseInt((result.rows[0] as any).count ?? "0", 10);
    if (count > 0) {
      log(`Field labels already seeded (${count} rows), skipping`, "seed");
      return;
    }
    await db.insert(zuluFieldLabels).values(FIELD_LABELS_DATA).onConflictDoNothing();
    log(`Seeded ${FIELD_LABELS_DATA.length} field labels into zulu_field_labels`, "seed");
  } catch (err: any) {
    log(`Field labels seed error: ${err.message}`, "seed");
  }
}
